// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SAN_ParallaxMap","status":true,"description":"パララックスマップ ver1.1.2\r\n遠景マップ風のマップ機能を提供します。","parameters":{"particleWidth":"48","particleHeight":"48"}}
];
